import os
from pymongo import MongoClient

from . import settings

AGENT_NAME = settings.AGENT_NAME


def get_database():

    # MONGODB_HOST_NAME="mongo"
    # MONGODB_DATABASE_NAME="database"
    # CONNECTION_STRING = "mongodb://mongo/database"

    CONNECTION_STRING = f"mongodb://{settings.MONGODB_HOST_NAME}/{settings.MONGODB_ADMIN_DATABASE_NAME}"
    client = MongoClient(CONNECTION_STRING)
    return client[settings.MONGODB_ADMIN_DATABASE_NAME]

# This is added so that many files can reuse the function get_database()
if __name__ == "__main__":
    # Get the database
    dbname = get_database()

db=get_database()
discord_message_collection=db[f'{AGENT_NAME}_discord_messages']
timmy_answers_collection=db[f'{AGENT_NAME}_timmy_answers']
timmy_answer_cache_collection=db[f'{AGENT_NAME}_timmy_answer_cache']

# All the messages generated by the model
generated_message_collection=db[f'{AGENT_NAME}_generated_messages']

discord_channel_collection=db[f'{AGENT_NAME}_discord_channels']
discord_user_collection=db[f'{AGENT_NAME}_discord_users']
discord_server_collection=db[f'{AGENT_NAME}_discord_servers']

duck_gpt=db[f'{AGENT_NAME}_gpt']
