import os

AGENT_NAME=os.environ.get('AGENT_NAME','duck')

MIN_TEMP=float(os.environ.get('MIN_TEMP',0.7))
MAX_TEMP=float(os.environ.get('MAX_TEMP',0.9))

MONGODB_HOST_NAME= os.environ.get('MONGODB_HOST_NAME', 'localhost')
MONGODB_ADMIN_DATABASE_NAME=os.environ.get('MONGODB_ADMIN_DATABASE_NAME','database')
MONGODB_ADMIN_USER_NAME=os.environ.get('MONGODB_ADMIN_USER_NAME','root')
MONGODB_ADMIN_USER_PASSWORD=os.environ.get('MONGODB_ADMIN_USER_PASSWORD','example')

DISCORD_TOKEN=os.environ['DISCORD_TOKEN']

DISCORD_CLIENT_USER_ID = os.environ.get('DISCORD_CLIENT_USER_ID')
DISCORD_CLIENT_USER_NAME = os.environ.get('DISCORD_CLIENT_USER_NAME')

# Where messages generated by the bot go by default.
DEFAULT_CHANNEL=os.environ['DEFAULT_CHANNEL']
DEFAULT_CHANNEL_NAME=os.environ['DEFAULT_CHANNEL_NAME']

model_path=f"/app/models/{AGENT_NAME}_gpt.v0.6.1/"

# The discord id of the author of the bot.
AUTHOR_ID=os.environ.get('AUTHOR_ID')
AUTHOR_NAME=os.environ.get('AUTHOR_NAME',"error")

# The discord channel id to use as a profile for the bot.
PROFILE_CHANNEL_ID=os.environ.get('PROFILE_CHANNEL_ID')
