name: Test Suite

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: make system-deps

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: make install

      - name: Build project
        run: make build


      - name: Run tests with coverage
        run: make coverage

      - name: Upload Python coverage
        uses: actions/upload-artifact@v4
        with:
          name: python-coverage
          path: coverage.xml

      - name: Run JS/TS tests with coverage
        run: make coverage-js

      - name: Upload JS coverage
        uses: actions/upload-artifact@v4
        with:
          name: js-coverage
          path: coverage

