name: Python Test Suite
permissions:
  contents: read

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      - name: Install dependencies
        run: make system-deps setup-core setup-python


      - name: Run tests
        run: make test-python-services
      # - name: Run tests with coverage
      #   run: make coverage

      - name: Upload Python coverage
        uses: actions/upload-artifact@v4
        with:
          name: python-coverage
          path: coverage.xml

      # - name: Upload JS coverage
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: js-coverage
      #     path: coverage
