
name: TS Test Suite
permissions:
  contents: read

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: make system-deps  setup-ts


      - name: Run tests
        run: make test-ts

      - name: Generate coverage
        run: make coverage-ts

      - name: Upload TS coverage
        uses: actions/upload-artifact@v4
        with:
          name: ts-coverage
          path: services/ts/**/coverage
